{{- $fullName := include "pact-broker.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-broker
  labels:
    pact.io/component: broker
    {{- include "pact-broker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      pact.io/component: broker
      {{- include "pact-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        pact.io/component: broker
        {{- include "pact-broker.selectorLabels" . | nindent 8 }}
    spec:
      # serviceAccountName: {{ $fullName }}
      # imagePullSecrets:
      # - name: {{ .Values.imagePullSecrets }}
      containers:
      - name: pact-broker
        image: '{{ .Values.pact_broker.image}}:{{ .Values.pact_broker.tag }}'
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: {{ $fullName }}
        env:
          - name: PACT_BROKER_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.existingSecret }}
                key: {{ .Values.postgresql.secretKey }}
        ports:
        - name: http
          protocol: TCP
          containerPort: 9292
        livenessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: Host
              value: {{ .Values.host }}
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: Host
              value: {{ .Values.host }}
          failureThreshold: {{ .Values.pact_broker.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.pact_broker.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.pact_broker.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.pact_broker.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.pact_broker.livenessProbe.timeoutSeconds }}
      {{- if .Values.metrics.enabled }}
      - name: pact-broker-exporter
        image: containersol/pactbroker_exporter:v0.1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: PB_EXPORTER_PACTBROKER_URI
          value: {{ include "pact-broker.hostname" . }}
        ports:
        - name: metricshttp
          protocol: TCP
          containerPort: 9624
      {{- end }}
