{{- if .Values.createPostgresqlSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  labels:
    app.kubernetes.io/name: {{ include "pact-broker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "pact-broker.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
{{- if .Values.postgresql.auth.password }}
  postgresql-postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{ .Values.postgresql.secretKey }}: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- else }}
  {{- $postgresRandomPassword := randAlphaNum 16 | b64enc | quote }}
  postgresql-postgres-password: {{ $postgresRandomPassword }}
  password: {{ $postgresRandomPassword }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ $postgresRandomPassword }}
{{- end }}
{{- end }}
