apiVersion: v1
kind: Service
metadata:
  name: {{ include "pact-broker.fullname" . }}
  labels:
    {{- include "pact-broker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.metrics.enabled }}
  - port: 9624
    targetPort: metricshttp
    protocol: TCP
    name: metricshttp
  {{- end }}
  selector:
    {{- include "pact-broker.selectorLabels" . | nindent 4 }}
