host: pact-broker.example
# since this secret should persist, only generate on first deploy
createPostgresqlSecret: false

pact_broker:
  image: pactfoundation/pact-broker
  tag: 2.106.0.1
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

postgresql:
  serviceAccount:
    enabled: true
  auth:
      username: pact_broker
      password: ""
      database: pact_broker
      existingSecret: pact-broker-postgresql
      secretKeys:
        userPasswordKey: postgres-password
  persistence:
    enabled: true
  replication:
    enabled: false
  service:
    port: 5432
  securityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    # runAsUser: 1001
  volumePermissions:
    enabled: true
    securityContext:
      # runAsUser: 1001

metrics:
  enabled: true

