host: pact-broker.example
# since this secret should persist, only generate on first deploy
createPostgresqlSecret: true

pact_broker:
  image: pactfoundation/pact-broker
  tag: 2.79.0.0
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 90
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 30

postgresql:
  serviceAccount:
    enabled: true 
  postgresqlUsername: pact_broker
  postgresqlPassword: ""
  postgresqlDatabase: pact_broker
  secretKey: postgresql-password
  existingSecret: postgresql-password
  persistence:
    enabled: true
  replication:
    enabled: false
  service:
    port: 5432
  securityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    # runAsUser: 1001
  volumePermissions:
    enabled: true
    securityContext:
      # runAsUser: 1001
