name: Generate values schema json
on:
  - pull_request
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Generate values schema json
      uses: tylerrasor/helm-values-schema-json-action@77c9f2d9403273e6c8d1be02bdf8f0c3cdcc98a7
      with:
        input: pact-broker/values.yaml
        output: pact-broker/values.schema.json
        git-push: true
        noAdditionalProperties: true
